### ISSUE TITLE
LinkedIn successful sign in redirect bug.

### ISSUE THREAD

**Issue by RylanGotto** [nraboy/ng-cordova-oauth#100]
Greetings!

I am having an issue with the LinkedIn function. After a successful login the Innappbrowser tries to redirect to the callback url, I am met with an error page for about 2/3rds of a second, saying page not found. After the 2/3rds of second I return back to the app and successfully complete my login flow. I have tried modifying the plugin so the browser closes immediately after a successful login however I am having no success. 

Any tips or suggestions would greatly appreciated, 

Cheers, Rylan.

**Comment by nraboy** [comment]
This is due to a race condition with providers that don't use implicit grants like LinkedIn.  The InAppBrowser processes requests faster than the API can produce and since technically Apache Cordova applications don't serve on localhost, it gets an error.

The only solution to fix this is to override the redirect_uri to a website that exists, not being served on localhost.  Use that same redirect_uri in the LinkedIn dashboard.

Best,

**Comment by RylanGotto** [comment]
Hey thanks for you reply, I have switched up the redirect_url. However, I am a little confused as to how I would give control back to ionic after the innappbrowser redirects to a URL which exists? Currently, after a successful sign in I am redirected to the URL but then it just stalls. I am not sure if it matters but I recently installed crosswalk

**Comment by noor92** [comment]
Hi, can you lease show me an example of how to code the redirect URI. I tried this but it didn't work:

```
$cordovaOauth.linkedin(LINKEDIN_OAUTH_ID, LINKEDIN_OAUTH_SECRET,redirectUri,["r_basicprofile", "r_emailaddress"],randomString()).then(function(result) 
	    {
	    	$scope.$storage.linkedInUser  = result.access_token
	    	console.log ($scope.$storage.linkedInUser )....
```
