### ISSUE TITLE
Should not use/require the client_secret

### ISSUE THREAD

**Issue by sflahave** [nraboy/ng-cordova-oauth#120]
I'm very new to OAuth 2. Having just finished reading the spec yesterday, along with this article by Alex Bilbie: http://alexbilbie.com/2014/11/oauth-and-javascript/ , 
my understanding is that using the client_secret in front-end code is fundamentally flawed. We cannot securely store the client_secret in any front-end application, including packaged "native" mobile applications. If we do, it should no longer be considered secret. Yet, this library requires a client_secret argument for the calls to github, digitalOcean, for example. Am I missing something?

**Comment by nraboy** [comment]
You are correct.  You should not use explicit grant types (ones with client secret) in your front-facing application because it is incredibly easy to decompile applications.

This library offers explicit grant providers for two reasons:

1. Not all providers offer implicit type grants (front-facing safe)
2. Developers will continue to ask for provider support from me regardless on how unsafe it might be and regardless on how many times I say no.  I gave up playing the role of cyber-nanny

With that said, I would like to tell you to use explicit grants in a front-facing application at your own risk.  You won't see me using them.  This library implements the oauth spec correctly regardless of security recommendations.

I'm glad you took the time to research oauth.  Shows you care about your users :-)

Best,
