### ISSUE TITLE
Dual mode browser and mobile device

### ISSUE THREAD

**Issue by psimondk** [nraboy/ng-cordova-oauth#15]
Hi,

Coenraets made an FB library where there was an ability to login even if you where not using a mobile device. Perhaps some of that code could be re-purposed to do the same for ng-cordova-oauth? 

https://github.com/ccoenraets/OpenFB

Btw. awesome libraries! :+1:

Brgds, Palle S

**Comment by nraboy** [comment]
It is a possibility, but I don't know how I feel about needing to include a callback HTML file for browser development.  It also would require testing through a locally hosted server to be able to get to `http://localhost`

It would add another layer of confusion to the library.

I'll think about it :)

**Comment by psimondk** [comment]
For debugging purposes it is really neat to be able to run all the code in
browser mode. ionic serve or similar should provide the needed web server.
Anyway I manage to get by using remote debugging, but it would be a very
welcome addition :)

Cheers, Palle

**Comment by nraboy** [comment]
I did more fiddling with this idea and I've come to the conclusion it is not a good decision.

The reason the OpenFB library works is because Facebook allows for implicit grant types.  Half of the providers in ng-cordova-oauth don't allow for implicit grants.

I'd rather it be an all or nothing deal otherwise I'm going to get a mess of inquiries with people asking why it doesn't work for such and such provider.  Even for the implicit grant types, there are extra levels of confusion.

You had a good thought, but ultimately, it is not appropriate for a mobile phone implementation.  As always, I encourage you to only test your mobile apps in a simulator or on a device.  Leave the web browsers for web sites.

Regards,

**Comment by psimondk** [comment]
Hi Nic,

Thanks for considering the proposal. I did not do the background checking
that you did.

I get by now with using a oneplus android device and chrome://inspect,
which is an ok solution for most of my debugging needs.

I agree with many of your statements on your Why i've gone hybrid blog and
surely ionic is a vast improvement over its predecessors in the hybrid
space.

All the best,
Palle
