### ISSUE TITLE
ion-google-place cannot work with ng-cordova-oauth

### ISSUE THREAD

**Issue by chicheongweng** [nraboy/ng-cordova-oauth#182]
See this thread. Not sure whether this is an ion-google-place issue or a ng-cordova-oauth issue.

https://github.com/israelidanny/ion-google-place/issues/63

**Comment by chicheongweng** [comment]
It turns out the name "google" is causing conflict. Consider renaming it to gmail.

**Comment by nraboy** [comment]
The Google API spans beyond Gmail so that wouldn't make sense.

I'm not in the business of fixing and supporting other libraries.  The URLs in the ticket you shared made it obvious that you were trying to use ionic serve, ionic live reload, or ionic view, all of which are unsupported with ng-cordova-oauth.  My assumption is there are errors on your end only.  There will be no further efforts in resolving your library.

My suggestion is having this other library developer find a fix, if there truly is an issue.

Regards,

cc @matheusrocha89
