### ISSUE TITLE
Example of retrieving additional data after login?

### ISSUE THREAD

**Issue by 5inline** [nraboy/ng-cordova-oauth#22]
I'm attempting to make a request to https://api.twitter.com/1.1/account/verify_credentials.json to retrieve the user profile information after login. 

Something like (which I can't seem to get working):

```
var oauthObject = {
	oauth_consumer_key : '[key]',
	oauth_nonce : $cordovaOauthUtility.createNonce(10),
	oauth_signature_method : 'HMAC-SHA1',
	oauth_timestamp : Math.round((new Date()).getTime() / 1000.0),
	oauth_version : "1.0",
	oauth_token : data.oauth_token // returned from $cordovaOauth.twitter()
};

var signatureObj = $cordovaOauthUtility.createSignature("GET", "https://api.twitter.com/1.1/account/verify_credentials.json", oauthObject, oauthObject, '[secret]');

$http(
	{
		method : 'JSONP',
		url : 'https://api.twitter.com/1.1/account/verify_credentials.json',
		params : angular.extend(oauthObject, {oauth_signature: signatureObj.signature})
	});
```

**Comment by nraboy** [comment]
I'm not familiar with the Twitter API.  This library was only intended to accomplish the Oauth login.  Everything beyond that was intended to be of your own design, imagination, and research.

With that said, what errors are you receiving?  Without having seen your errors, my first assumption is you're getting an invalid signature, probably because you are not creating a signature with BOTH the client secret key and token secret.  However, I don't know for sure without your errors.

Regards,

**Comment by 5inline** [comment]
Ah, gotcha. Just looking for some additional guidance.

You are correct though, I am getting a signature issue. Are you saying where the [secret] is? What should be there? consumer_secret +'&'+ oauth_token_secret ?

**Comment by nraboy** [comment]
The `$cordovaOauthUtility.createSignature` method takes an optional final parameter for the oauth_token_secret.  If found it will sign with both the consumer secret and token secret.
