### ISSUE TITLE
Callback Uri can not load Twitter

### ISSUE THREAD

**Issue by sadanandGithub123** [nraboy/ng-cordova-oauth#232]
Hello...
I am using ng-cordova-oauth for authenticate my app with twitter. i have set callback uri as "http://tinyurl.com/krmpchb" which is representing to http://localhost/calback.

when i try to login it returns me access token but throug error as -
![twittererr](https://cloud.githubusercontent.com/assets/9443045/14071064/fbc736f8-f4cc-11e5-91f3-bac5618dfd17.png)

**Comment by nraboy** [comment]
This is due to a race condition in explicit grant providers like Twitter.  Providers that use explicit grants were never intended to be used client side.

The only way to get around this would be to host your own callback and override the callback via the Twitter connection.  If the page exists, the error will not be thrown.

Best,

**Comment by daltonpereira** [comment]
@nraboy  Facing the same issue. so if upload a blank callback.html and specify www.mydomain/callback.html in the twitter application as well as your auth js file it should not throw an error right?

**Comment by daltonpereira** [comment]
@nraboy It worked! :+1:
