### ISSUE TITLE
$cordovaOauth.twitter() return null

### ISSUE THREAD

**Issue by edgarnsr** [nraboy/ng-cordova-oauth#256]
Hi everyone. I have an issue with twitter authentication, when I try to connect always return null, I detect this issue when I installed [https://github.com/apache/cordova-plugin-wkwebview-engine](url). When I remove wkwebview all works fine.
I tried other alternative: [https://github.com/Telerik-Verified-Plugins/WKWebView](url) but is the same result.

Regards.

**Comment by nraboy** [comment]
This library relies heavily on the stock Apache Cordova web view.  Replacing it will likely cause this plugin to fail.  There are no plans to support anything beyond the stock web view.

Best,

**Comment by SeanHub** [comment]
Cordova iOS 4.0+ is the default iOS version and pushes to WKWebView: [https://cordova.apache.org/announcements/2015/12/08/cordova-ios-4.0.0.html](Cordova 4.0.0)

Now that I have the latest Cordova iOS (4.1.1) ng-cordova-oauth no longer works. The application now runs off a local web server, but because of this, Twitter will not accept connections from localhost. Localhost is needed when using WKWebView. Ergo, this plugin does not work with Twitter OAuth when using the latest and greatest of Cordova iOS.

**Comment by nraboy** [comment]
I tested others recently and they worked fine.  I will try Twitter again

**Comment by edgarnsr** [comment]
I think the same that SeanHub, so I searched an alternative and I found [http://www.justin-credible.net/2015/12/31/use-wkwebview-in-your-cordova-app-without-a-local-web-server/](http://www.justin-credible.net/2015/12/31/use-wkwebview-in-your-cordova-app-without-a-local-web-server/).
I followed the instructions but still Twitter OAuth does not work

**Comment by nraboy** [comment]
Just tested Twitter with the following Apache Cordova platform versions:

```
{
    "ios": "4.1.1",
    "android": "5.1.1"
}
```

Those were taken from my **platforms/platforms.json** file.  I also validated the version of my platforms with `cordova platform check`.

I received no errors.  I received an access token exactly as expected.
