### ISSUE TITLE
How to get refresh token with spotify oauth

### ISSUE THREAD

**Issue by fquirogam** [nraboy/ng-cordova-oauth#328]
Is there anyway to get refresh token from the spotify oauth? I'm only getting the accessToken

**Comment by nraboy** [comment]
Spotify offers an implicit grant solution so it was used in favor of the explicit alternative.  Implicit grants do not issue refresh tokens as they are designed for client facing applications.

While some providers in this library use explicit grants, it is best to have them done server side due to the client secret key.

Best,

**Comment by fquirogam** [comment]
So, for me (since from access_token there is no way to get the refresh token) I have to completely ignore this library and make my own authentication flow?

**Comment by nraboy** [comment]
Access tokens have expiration times.  You have a few options:

1. Ask the user to sign in again after the token expires
2. Get the authorization code via the library and complete the flow server side and let your server manage the refresh token
3. Implement your own oauth flow

I encourage you to read about oauth, implicit grants, and explicit grants and fully understand what is happening with each.  Your users will appreciate proper security within your application.

Best,
