### ISSUE TITLE
code and token needed for google plus 

### ISSUE THREAD

**Issue by mzarella** [nraboy/ng-cordova-oauth#34]
Hello again. I successfully have this working with Google, but the problem is that the access token expires in an hour. To get around this problem, Google recommends a [hybrid server-side flow](https://developers.google.com/+/web/signin/server-side-flow) *"where a user authorizes your app on the client side using the JavaScript API client and you send a special one-time authorization code to your server"*. However, to implement, I need the access code returned by Google and this library only returns the token.

Thanks again for your help and excellent open source libraries.

**Comment by nraboy** [comment]
I've set ngCordova to use implicit grants whenever possible since it adheres to the client side guidelines.  This results in a token that expires after time and cannot be refreshed without signing in again.

If you need more information in the request to make it work with your third party tools, I suggest you fork this repository.

Regards,

**Comment by nraboy** [comment]
Also, access code probably is the same as access token.

All other tokens such as request tokens would be useless to keep.

Regards,
