### ISSUE TITLE
Is there a way to make it work in the browser

### ISSUE THREAD

**Issue by casertap** [nraboy/ng-cordova-oauth#46]
I would like to know if it is possible to perform the authentication with facebook using the browser because I get the error "Cannot authenticate via a web browser".

I am wondering also what is the main difference between the ng-cordova-oauth project and the ng-cordova with the $cordovaOauth plugin?

Thanks

**Comment by nraboy** [comment]
I am the maintainer of both ng-cordova-oauth and ng-cordova.  Since this is a hobby of mine, ng-cordova gets updated slower because my time is short.

I purposefully added that browser error because it is never going to work in a browser due to the localhost callbacks and lack of control that the platforms offer.

Like I tell most people, you're developing mobile apps not websites.  Don't test your apps in the browser.

Regards,

**Comment by codingyourlife** [comment]
@nraboy I would like to use "ionic serve --address 192.168.178.XXX" and call that ip with port 8100 on my phone in chrome. That's not easily possible because of your "feature". I could test like 90% of the functionality of my app and having instant updates while developing. Are you sure you don't want to change this? Would save me a lot of time.

**Comment by nraboy** [comment]
Ionic serve is not compatible.  I have the library throw errors because it was too tiring trying to debug peoples problems, when it was ionic serve all along.

I didn't remove it because I wanted to.  I removed it because it won't work.

Regards,
