### ISSUE TITLE
Persistent sign in

### ISSUE THREAD

**Issue by alexislg2** [nraboy/ng-cordova-oauth#58]
Hey,
Thank you for your very useful lib. Works great. But one question:
- how do you handle persistent login? With your plugin, the user has to sign almost each times the app starts. This is a real problem. On the apps I use everyday I just have to sign in once and then it's working fine until I log out.

Any idea to implement this securely?

**Comment by nraboy** [comment]
You have to store your access_token and expires_in value in local storage and do a check before trying to sign in.  If the token exists and it hasn't expired, bypass the oauth process, otherwise go through it.

Oauth for client facing applications should never use a refresh token.  I have chosen not to include them in my library for security reasons.  Because of this, access_token values typically expire within one hour.

Regards,

**Comment by dcbartlett** [comment]
This problem with this is that Google gives back a TTL of 3600, this is VERY short for a "native" app.  Most app developers what to have "persistent" login experience for the user.  Without having a "refresh token" we can't ask google for a new auth token to use the API without asking the user for their credentials again.

**Comment by nraboy** [comment]
Storing a refresh token in a client facing application is a very bad idea.  This is why implicit oauth grants were created for JavaScript and similar scenarios.

If you don't care about user security, you should be able to change the library pretty easy to use Google's explicit grant option.  If you care about user security, then the 3600 is the price to pay.  Otherwise introduce your own middleman server that handles the auth requests.

Regards,
