### ISSUE TITLE
Error: Could not find InAppBrowser plugin when using in ionic

### ISSUE THREAD

**Issue by mypark** [nraboy/ng-cordova-oauth#62]
followed the instructions in the readme to add the to the project and also added the plugin to cordova using

`cordova plugin add https://git-wip-us.apache.org/repos/asf/cordova-plugin-inappbrowser.git`

 but am getting the error " Could not find InAppBrowser plugin"

**Comment by MyBoon** [comment]
Try **cordova plugin add org.apache.cordova.inappbrowser** instead.

**Comment by mypark** [comment]
that did it!

**Comment by ykarthikreddy18** [comment]
Hi @MyBoon  @mypark .. I tried to install "cordova plugin add org.apache.cordova.inappbrowser", but it is downloading cordova-plugin-inappbrowser instead of org.apache.cordova.inappbrowser.. Below is the message shown while installing the plugin ...
Notice: org.apache.cordova.inappbrowser has been automatically converted to cord
ova-plugin-inappbrowser and fetched from npm. This is due to our old plugins reg
istry shutting down.

Can u please help  me..

**Comment by nraboy** [comment]
cordova-plugin-inappbrowser should be fine

**Comment by MyBoon** [comment]
`cordova-plugin-inappbrowser` should work now
