### ISSUE TITLE
Twitter and Instagram Callback URL

### ISSUE THREAD

**Issue by jokerxvier** [nraboy/ng-cordova-oauth#65]
Hi I'm having an issue with the callback after the user login with twitter or instagram it will be redirected to another page that says  "Web page not available The web page at http://localhost/callback/?oath_token=......................" How can i fixed this to not redirect to the callback url or closed automatically inApp after the callback? any help? thanks

**Comment by nraboy** [comment]
This will always happen for providers that use explicit grants.  It is due to a race condition.  The browser must remain open until the POST request completes, so if the POST request is slow, then the browser will have no choice to display a problem.

The only way around this is by introducing server side code, which many people are not willing to do.

**Comment by jokerxvier** [comment]
what do you mean by server side cause i'm willing to try the server side..?

**Comment by nraboy** [comment]
Well, in the $cordovaOauth providers, it doesn't really matter what callback you use as long as you define it.

For example if you set the callback via Twitter and Instagram to http://www.examplesite.com/oauth_callback.html, and oauth_callback.html exists, it will show your page rather than an error message.  You just need to put that same page in the plugin source.

Does that make sense?

Regards,

**Comment by jokerxvier** [comment]
hi this fixed my issue with redirection. thanks for the help.

**Comment by Sam747** [comment]
@jokerxvier I am facing the same issue plz tell me how did you deploy it
